version: "3.9"
services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: torail
      POSTGRES_USER: torail
      POSTGRES_PASSWORD: torail_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: .                # ← ルートをビルドコンテキストに
      dockerfile: Dockerfile.backend  # ← ファイル名をそのまま指定
    env_file: .env              # 必要なら.envを置く
    volumes:
      - .:/app                   # ホストのルートを/appにマウント
    ports:
      - "8000:8000"
    command: >
      sh -c "python manage.py migrate &&
             gunicorn Torail.wsgi:application --bind 0.0.0.0:${PORT:-8000}"


 # ---------- ② Celery Worker ----------
  worker:
    build: ./backend
    command: celery -A Torail worker --loglevel=info
    volumes:
      - ./backend:/app
    env_file: ./backend/.env
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/1

  # ---------- ③ Redis ----------
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    depends_on:
      - backend
    # ホストのコードはマウントするが、node_modules はコンテナ側を優先
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"

volumes:
  postgres_data:

# docker compose up --build -d
# docker compose down